# Generated by Django 5.2.5 on 2025-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фотография'),
        ),
    ]
