# Generated by Django 5.2.5 on 2025-09-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
